/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Classes.DBManager;
import Classes.Debt;
import Classes.Person;
import static java.awt.SystemColor.text;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/** Control Panel View
 * this is the main control panel for the application
 *
 * @author Ross Duncan
 * 30/04/2020
 */
public class ControlPanel extends javax.swing.JFrame {

    
    //Hashmap for storing debtees as they are loaded in
    private HashMap<Integer, Person> debtees = new HashMap<>();
    //Hashmap for storing debts as they are loaded in
    private HashMap<Integer, Debt> debts = new HashMap<>();
    //Load dbManager
    private DBManager db = new DBManager();;
    //Double for sotring the total debt of the user
    private double totalDebt = 0.00;
    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
        
        //Calls the method to load the table
        LoadTables();
        
        
        tblDebtees.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event){
                //Clear the debts hashmap
                debts.clear();
                
                //Get model of the debtees table
                DefaultTableModel model = (DefaultTableModel)tblDebtees.getModel(); 
                
                //The if statement fixes a crash when reloading table, the applicaiton would crash because
                //when the tables reload there is no selected value but the listener would attempt to get
                //the selected value anyway
                if(tblDebtees.getSelectedRow() != -1) 
                {
                    //Get the selected debtees ID
                    int debteeIDT = Integer.parseInt(String.valueOf(model.getValueAt(tblDebtees.getSelectedRow(), 0)));

                    //Load the selcted debtees debts from the database into the debts hashmap
                    debts = db.loadIndividualDebts(debts, debteeIDT);
                }
                
                //get the table model of the debts table
                model = (DefaultTableModel)tblDebts.getModel();
                //deletes any existing rows from the table
                model.setRowCount(0);

                //Loop through the hashmap of debtees and add them to the debtees table
                for(Map.Entry<Integer, Debt> entry : debts.entrySet())
                {
                    //Get the current person(debtee) in the entry set
                    Debt debtToAdd = entry.getValue();

                    //add that person to the debtees table
                    model.addRow(new Object[] 
                    {debtToAdd.getDebtID(), debtToAdd.getDebtName(), debtToAdd.getDebteeID(), "£" +  String.format("%.02f", debtToAdd.getAmount()), debtToAdd.getDOD()});
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDebtees = new javax.swing.JTable();
        btnAddNewDebtee = new javax.swing.JButton();
        btnViewDebtee = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        btnAddNewDebt = new javax.swing.JButton();
        btnRemoveDebtee = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDebts = new javax.swing.JTable();
        btnRemoveDebt = new javax.swing.JButton();
        btnShowAllDebts = new javax.swing.JButton();
        lblTotalDebt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DesktopDebter - Control Panel");
        setResizable(false);

        tblDebtees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Debtee", "Total Debt Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDebtees.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblDebteesPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblDebtees);

        btnAddNewDebtee.setText("Add New Debtee");
        btnAddNewDebtee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewDebteeActionPerformed(evt);
            }
        });

        btnViewDebtee.setText("View Debtee");
        btnViewDebtee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDebteeActionPerformed(evt);
            }
        });

        lblMessage.setText("Message");

        btnAddNewDebt.setText("Add New Debt");
        btnAddNewDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewDebtActionPerformed(evt);
            }
        });

        btnRemoveDebtee.setText("Remove Debtee");
        btnRemoveDebtee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDebteeActionPerformed(evt);
            }
        });

        tblDebts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DebtID", "Debt Name", "Debtee", "Amount", "DOD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDebts);

        btnRemoveDebt.setText("Remove Debt");
        btnRemoveDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDebtActionPerformed(evt);
            }
        });

        btnShowAllDebts.setText("Show All Debts");
        btnShowAllDebts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllDebtsActionPerformed(evt);
            }
        });

        lblTotalDebt.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTotalDebt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalDebt.setText("Current Total Debt: £0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalDebt)
                .addGap(242, 242, 242))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMessage)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddNewDebtee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewDebtee)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveDebtee)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddNewDebt)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveDebt)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowAllDebts))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTotalDebt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddNewDebt)
                        .addComponent(btnRemoveDebt)
                        .addComponent(btnShowAllDebts))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddNewDebtee)
                        .addComponent(btnViewDebtee)
                        .addComponent(btnRemoveDebtee)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewDebteeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewDebteeActionPerformed
        AddDebtee ad = new AddDebtee();
        this.dispose();
        ad.setVisible(true);
    }//GEN-LAST:event_btnAddNewDebteeActionPerformed

    private void btnViewDebteeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDebteeActionPerformed
        //If a debtee has been selected from the table
        if(tblDebtees.getSelectedRow() != -1) 
        {
            //Get model of the debtees table
            DefaultTableModel model = (DefaultTableModel)tblDebtees.getModel(); 
            //Get the selected debtees ID
            int debteeID = Integer.parseInt(String.valueOf(model.getValueAt(tblDebtees.getSelectedRow(), 0)));
            //Get the selected debtees name
            String debteeName = String.valueOf(model.getValueAt(tblDebtees.getSelectedRow(), 1));
            //Open view debtees view passing in the selected debtees ID
            ViewDebtee vd = new ViewDebtee(debteeID, debteeName);
            this.dispose();
            vd.setVisible(true);
        }
        else
        {
            lblMessage.setText("Please Select A Debtee from the table first");
        }
    }//GEN-LAST:event_btnViewDebteeActionPerformed

    private void btnAddNewDebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewDebtActionPerformed
        //If a debtee has been selected from the table
        if(tblDebtees.getSelectedRow() != -1) 
        {
            //Get model of the debtees table
            DefaultTableModel model = (DefaultTableModel)tblDebtees.getModel(); 
            //Get the selected debtees ID
            int debteeID = Integer.parseInt(String.valueOf(model.getValueAt(tblDebtees.getSelectedRow(), 0)));
            //Get the selected debtees name
            String debteeName = String.valueOf(model.getValueAt(tblDebtees.getSelectedRow(), 1));
            //Open view debtees view passing in the selected debtees ID
            AddDebt ad = new AddDebt(debteeID, debteeName);
            this.dispose();
            ad.setVisible(true);
        }
        else
        {
            lblMessage.setText("Please Select A Debtee from the table first");
        }
    }//GEN-LAST:event_btnAddNewDebtActionPerformed

    private void btnRemoveDebteeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDebteeActionPerformed
        //If a debtee has been selected from the table
        if(tblDebtees.getSelectedRow() != -1) 
        {
            //Get model of the debtees table
            DefaultTableModel model = (DefaultTableModel)tblDebtees.getModel(); 
            //Get the selected debtees ID
            int debteeID = Integer.parseInt(String.valueOf(model.getValueAt(tblDebtees.getSelectedRow(), 0)));
            //Call the DBManager method remove this debtee from the database
            db.removeDebtee(debteeID);
            
            //calls the method to load the table, basically updating it by reloading it
            LoadTables();
        }
        else
        {
            lblMessage.setText("Please Select A Debtee from the table first");
        }
    }//GEN-LAST:event_btnRemoveDebteeActionPerformed

    private void btnRemoveDebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDebtActionPerformed
        //If a debt has been selected from the table
        if(tblDebts.getSelectedRow() != -1) 
        {
            //Get model of the debts table
            DefaultTableModel model = (DefaultTableModel)tblDebts.getModel(); 
            //Get the selected debts ID
            int debtID = Integer.parseInt(String.valueOf(model.getValueAt(tblDebts.getSelectedRow(), 0)));
            //Call the DBManager method to remove the debt from the database
            db.removeDebt(debtID);
            
            //calls the method to load the table, basically updating it by reloading it
            LoadTables();
        }
        else
        {
            lblMessage.setText("Please Select A Debt from the debts table first");
        }
    }//GEN-LAST:event_btnRemoveDebtActionPerformed

    private void tblDebteesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblDebteesPropertyChange

    }//GEN-LAST:event_tblDebteesPropertyChange

    private void btnShowAllDebtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllDebtsActionPerformed
        LoadTables();
    }//GEN-LAST:event_btnShowAllDebtsActionPerformed

    
    private void LoadTables()
    {       
        //DEBTEES TABLE
        //Clear the debtees hashmap
        debtees.clear();
        //Load the users debtees from the database into the debtees hashmap
        debtees = db.loadPeople(debtees);
        
        //Create a table model and assign it the table model of the debtees table
        DefaultTableModel model = (DefaultTableModel)tblDebtees.getModel();
        //deletes any existing rows from the table
        model.setRowCount(0);
        
        //Loop through the hashmap of debtees and add them to the debtees table
        for(Map.Entry<Integer, Person> entry : debtees.entrySet())
        {
            //Get the current person(debtee) in the entry set
            Person personToAdd = entry.getValue();
            //add that person to the debtees table
            model.addRow(new Object[] 
            {personToAdd.getPeopleID(), personToAdd.getFirstName() + " " + personToAdd.getLastName(), "£" +  String.format("%.02f", personToAdd.getTotalDebt())});
        }
        
        //DEBTS TABLE
        //Clear the debts hashmap
        debts.clear();
        //Load the users debts from the database into the debts hashmap
        debts = db.loadDebts(debts);
        //get the table model of the debts table
        model = (DefaultTableModel)tblDebts.getModel();
        //deletes any existing rows from the table
        model.setRowCount(0);
        
        //Loop through the hashmap of debtees and add them to the debtees table
        for(Map.Entry<Integer, Debt> entry : debts.entrySet())
        {
            //Get the current person(debtee) in the entry set
            Debt debtToAdd = entry.getValue();
            
            //add that person to the debtees table
            model.addRow(new Object[] 
            {debtToAdd.getDebtID(), debtToAdd.getDebtName(), debtToAdd.getDebteeID(), "£" +  String.format("%.02f", debtToAdd.getAmount()), debtToAdd.getDOD()});
        }
        
        calculateTotalDebt();
        lblMessage.setText("");   
    }
    
    public void calculateTotalDebt()
    {
        totalDebt = 0.00;
        //Loop through the hashmap of debtees and add there debt to total debt
        for(Map.Entry<Integer, Person> entry : debtees.entrySet())
        {
            //Get the current person(debtee) in the entry set
            Person pd = entry.getValue();
            
            totalDebt = totalDebt + pd.getTotalDebt();
        }
        
        lblTotalDebt.setText("Current Total Debt: £" + String.format("%.02f",totalDebt));
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewDebt;
    private javax.swing.JButton btnAddNewDebtee;
    private javax.swing.JButton btnRemoveDebt;
    private javax.swing.JButton btnRemoveDebtee;
    private javax.swing.JButton btnShowAllDebts;
    private javax.swing.JButton btnViewDebtee;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTotalDebt;
    private javax.swing.JTable tblDebtees;
    private javax.swing.JTable tblDebts;
    // End of variables declaration//GEN-END:variables
}
