/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Classes.DBManager;
import Classes.Debt;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/** ViewDebtee view
 this is the menu for view the debts you owe to/owed by individual debtees
 *
 * @author Ross Duncan
 * 01/05/2020
 */
public class ViewDebtee extends javax.swing.JFrame {

    //Passed in debtee being viewed
    private int viewedDebteeID;
    //String for storing viewed debtees name
    private String debteeName;
    //Load DBManager
    private DBManager db = new DBManager();
    //Hashmap for storing debts tied to this debtee
    private HashMap<Integer, Debt> debts = new HashMap<>();
    
    /**
     * Creates new form ViewDebtees
     */
    public ViewDebtee(int viewedDebteeIDIn, String debteeNameIn) {
        initComponents();
        
        //Assign passed in debteeID to the viewDebteeId variable
        viewedDebteeID = viewedDebteeIDIn;
        //Assign passed in debteeName to debteeName variable
        debteeName = debteeNameIn;
        
        //Load debts for this debtee into debts hashmap
        debts = db.loadIndividualDebts(debts, viewedDebteeID);
        
        //Create a table model and assign it the table model of the debts table
        DefaultTableModel model = (DefaultTableModel)tblDebts.getModel(); 
        for(Map.Entry<Integer, Debt> entry : debts.entrySet()) //loop through the orders hashmap
        {
            Debt debtToAdd = entry.getValue();//initalize and assign actualOrder
            
            //add current order in loop to table as a row
            model.addRow(new Object[] 
            {debtToAdd.getDebtID(), debtToAdd.getDebtName(), debtToAdd.getAmount(), 
                debtToAdd.getDOD(), debtToAdd.getNotes()});
        }
        
        //Sets title to display debtees name
        lblDebteeName.setText(debteeName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDebts = new javax.swing.JTable();
        lblDebteeName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAddDebt = new javax.swing.JButton();
        btnRemoveDebtee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDebts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Debt", "Value", "DOD", "Notes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDebts);

        lblDebteeName.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblDebteeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDebteeName.setText("Name of Debtee");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddDebt.setText("Add Debt");
        btnAddDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDebtActionPerformed(evt);
            }
        });

        btnRemoveDebtee.setText("Remove This Debtee");
        btnRemoveDebtee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDebteeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(lblDebteeName))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnRemoveDebtee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddDebt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDebteeName)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddDebt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoveDebtee)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //Open Control Panel Menu and Close This Menu
        ControlPanel cp = new ControlPanel();
        this.dispose();
        cp.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddDebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDebtActionPerformed
        //Open add debt Menu, passing in the viewed debtee ID and the viewed Debtees name and Close This Menu
        AddDebt ad = new AddDebt(viewedDebteeID, debteeName);
        this.dispose();
        ad.setVisible(true);
    }//GEN-LAST:event_btnAddDebtActionPerformed

    private void btnRemoveDebteeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDebteeActionPerformed
        
        db.removeDebtee(viewedDebteeID);
        
        //Open view debtees view passing in the selected debtees ID
        ControlPanel cp = new ControlPanel();
        this.dispose();
        cp.setVisible(true);
    }//GEN-LAST:event_btnRemoveDebteeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDebtee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDebtee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDebtee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDebtee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new ViewDebtee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDebt;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemoveDebtee;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDebteeName;
    private javax.swing.JTable tblDebts;
    // End of variables declaration//GEN-END:variables
}
